--[[

######## #### ##    ## ##    ## ##        #######   ######  ##    ## ######## ########  
##        ##  ###   ## ###   ## ##       ##     ## ##    ## ##   ##  ##       ##     ## 
##        ##  ####  ## ####  ## ##       ##     ## ##       ##  ##   ##       ##     ## 
######    ##  ## ## ## ## ## ## ##       ##     ## ##       #####    ######   ##     ## 
##        ##  ##  #### ##  #### ##       ##     ## ##       ##  ##   ##       ##     ## 
##        ##  ##   ### ##   ### ##       ##     ## ##    ## ##   ##  ##       ##     ## 
##       #### ##    ## ##    ## ########  #######   ######  ##    ## ######## ########  

@file    client/clienttables.lua
@author  Finn
@company FinnLocked
@date    01-09-2026
@license MIT

]]

ClientTables = {}

ClientTables.WeaponNames = {
    [tostring(GetHashKey("WEAPON_UNARMED"))] = "Unarmed",
    [tostring(GetHashKey("GADGET_PARACHUTE"))] = "Parachute",
    [tostring(GetHashKey("WEAPON_KNIFE"))] = "Knife",
    [tostring(GetHashKey("WEAPON_NIGHTSTICK"))] = "Nightstick",
    [tostring(GetHashKey("WEAPON_HAMMER"))] = "Hammer",
    [tostring(GetHashKey("WEAPON_BAT"))] = "Baseball Bat",
    [tostring(GetHashKey("WEAPON_CROWBAR"))] = "Crowbar",
    [tostring(GetHashKey("WEAPON_GOLFCLUB"))] = "Golf Club",
    [tostring(GetHashKey("WEAPON_BOTTLE"))] = "Bottle",
    [tostring(GetHashKey("WEAPON_DAGGER"))] = "Antique Cavalry Dagger",
    [tostring(GetHashKey("WEAPON_HATCHET"))] = "Hatchet",
    [tostring(GetHashKey("WEAPON_KNUCKLE"))] = "Knuckle Duster",
    [tostring(GetHashKey("WEAPON_MACHETE"))] = "Machete",
    [tostring(GetHashKey("WEAPON_FLASHLIGHT"))] = "Flashlight",
    [tostring(GetHashKey("WEAPON_SWITCHBLADE"))] = "Switchblade",
    [tostring(GetHashKey("WEAPON_BATTLEAXE"))] = "Battleaxe",
    [tostring(GetHashKey("WEAPON_POOLCUE"))] = "Pool Cue",
    [tostring(GetHashKey("WEAPON_PIPEWRENCH"))] = "Wrench",
    [tostring(GetHashKey("WEAPON_STONE_HATCHET"))] = "Stone Hatchet",
    [tostring(GetHashKey("WEAPON_GARBAGEBAG"))] = "Garbage Bag",
    [tostring(GetHashKey("WEAPON_HANDCUFFS"))] = "Handcuffs",
    [tostring(GetHashKey("WEAPON_CANDYCANE"))] = "Candy Cane",
    [tostring(GetHashKey("WEAPON_STUNROD"))] = "The Shocker",

    [tostring(GetHashKey("WEAPON_PISTOL"))] = "Pistol",
    [tostring(GetHashKey("WEAPON_PISTOL_MK2"))] = "Pistol Mk2",
    [tostring(GetHashKey("WEAPON_COMBATPISTOL"))] = "Combat Pistol",
    [tostring(GetHashKey("WEAPON_PISTOL50"))] = "Pistol .50",
    [tostring(GetHashKey("WEAPON_SNSPISTOL"))] = "SNS Pistol",
    [tostring(GetHashKey("WEAPON_SNSPISTOL_MK2"))] = "SNS Pistol Mk2",
    [tostring(GetHashKey("WEAPON_HEAVYPISTOL"))] = "Heavy Pistol",
    [tostring(GetHashKey("WEAPON_VINTAGEPISTOL"))] = "Vintage Pistol",
    [tostring(GetHashKey("WEAPON_MARKSMANPISTOL"))] = "Marksman Pistol",
    [tostring(GetHashKey("WEAPON_REVOLVER"))] = "Heavy Revolver",
    [tostring(GetHashKey("WEAPON_REVOLVER_MK2"))] = "Heavy Revolver Mk2",
    [tostring(GetHashKey("WEAPON_DOUBLEACTION"))] = "Double-Action Revolver",
    [tostring(GetHashKey("WEAPON_APPISTOL"))] = "AP Pistol",
    [tostring(GetHashKey("WEAPON_STUNGUN"))] = "Stun Gun",
    [tostring(GetHashKey("WEAPON_FLAREGUN"))] = "Flare Gun",
    [tostring(GetHashKey("WEAPON_RAYPISTOL"))] = "Up-n-Atomizer",
    [tostring(GetHashKey("WEAPON_CERAMICPISTOL"))] = "Ceramic Pistol",
    [tostring(GetHashKey("WEAPON_NAVYREVOLVER"))] = "Navy Revolver",
    [tostring(GetHashKey("WEAPON_GADGETPISTOL"))] = "Perico Pistol",
    [tostring(GetHashKey("WEAPON_PISTOLXM3"))] = "WM 29 Pistol",

    [tostring(GetHashKey("WEAPON_MICROSMG"))] = "Micro SMG",
    [tostring(GetHashKey("WEAPON_MACHINEPISTOL"))] = "Machine Pistol",
    [tostring(GetHashKey("WEAPON_MINISMG"))] = "Mini SMG",
    [tostring(GetHashKey("WEAPON_SMG"))] = "SMG",
    [tostring(GetHashKey("WEAPON_SMG_MK2"))] = "SMG Mk2",
    [tostring(GetHashKey("WEAPON_ASSAULTSMG"))] = "Assault SMG",
    [tostring(GetHashKey("WEAPON_COMBATPDW"))] = "Combat PDW",
    [tostring(GetHashKey("WEAPON_TECPISTOL"))] = "Tactical SMG",

    [tostring(GetHashKey("WEAPON_ASSAULTRIFLE"))] = "Assault Rifle",
    [tostring(GetHashKey("WEAPON_ASSAULTRIFLE_MK2"))] = "Assault Rifle Mk2",
    [tostring(GetHashKey("WEAPON_CARBINERIFLE"))] = "Carbine Rifle",
    [tostring(GetHashKey("WEAPON_CARBINERIFLE_MK2"))] = "Carbine Rifle Mk2",
    [tostring(GetHashKey("WEAPON_ADVANCEDRIFLE"))] = "Advanced Rifle",
    [tostring(GetHashKey("WEAPON_SPECIALCARBINE"))] = "Special Carbine",
    [tostring(GetHashKey("WEAPON_SPECIALCARBINE_MK2"))] = "Special Carbine Mk2",
    [tostring(GetHashKey("WEAPON_BULLPUPRIFLE"))] = "Bullpup Rifle",
    [tostring(GetHashKey("WEAPON_BULLPUPRIFLE_MK2"))] = "Bullpup Rifle Mk2",
    [tostring(GetHashKey("WEAPON_COMPACTRIFLE"))] = "Compact Rifle",
    [tostring(GetHashKey("WEAPON_MILITARYRIFLE"))] = "Military Rifle",
    [tostring(GetHashKey("WEAPON_HEAVYRIFLE"))] = "Heavy Rifle",
    [tostring(GetHashKey("WEAPON_TACTICALRIFLE"))] = "Service Carbine",
    [tostring(GetHashKey("WEAPON_BATTLERIFLE"))] = "Battle Rifle",
    [tostring(GetHashKey("WEAPON_STRICKLER"))] = "El Strickler",

    [tostring(GetHashKey("WEAPON_MG"))] = "MG",
    [tostring(GetHashKey("WEAPON_COMBATMG"))] = "Combat MG",
    [tostring(GetHashKey("WEAPON_COMBATMG_MK2"))] = "Combat MG Mk2",
    [tostring(GetHashKey("WEAPON_GUSENBERG"))] = "Gusenberg Sweeper",
    [tostring(GetHashKey("WEAPON_RAYCARBINE"))] = "Unholy Hellbringer",

    [tostring(GetHashKey("WEAPON_PUMPSHOTGUN"))] = "Pump Shotgun",
    [tostring(GetHashKey("WEAPON_PUMPSHOTGUN_MK2"))] = "Pump Shotgun Mk2",
    [tostring(GetHashKey("WEAPON_SAWNOFFSHOTGUN"))] = "Sawed-Off Shotgun",
    [tostring(GetHashKey("WEAPON_BULLPUPSHOTGUN"))] = "Bullpup Shotgun",
    [tostring(GetHashKey("WEAPON_ASSAULTSHOTGUN"))] = "Assault Shotgun",
    [tostring(GetHashKey("WEAPON_MUSKET"))] = "Musket",
    [tostring(GetHashKey("WEAPON_HEAVYSHOTGUN"))] = "Heavy Shotgun",
    [tostring(GetHashKey("WEAPON_DBSHOTGUN"))] = "Double Barrel Shotgun",
    [tostring(GetHashKey("WEAPON_AUTOSHOTGUN"))] = "Sweeper Shotgun",
    [tostring(GetHashKey("WEAPON_COMBATSHOTGUN"))] = "Combat Shotgun",

    [tostring(GetHashKey("WEAPON_SNIPERRIFLE"))] = "Sniper Rifle",
    [tostring(GetHashKey("WEAPON_HEAVYSNIPER"))] = "Heavy Sniper",
    [tostring(GetHashKey("WEAPON_HEAVYSNIPER_MK2"))] = "Heavy Sniper Mk2",
    [tostring(GetHashKey("WEAPON_MARKSMANRIFLE"))] = "Marksman Rifle",
    [tostring(GetHashKey("WEAPON_MARKSMANRIFLE_MK2"))] = "Marksman Rifle Mk2",
    [tostring(GetHashKey("WEAPON_PRECISIONRIFLE"))] = "Precision Rifle",

    [tostring(GetHashKey("WEAPON_GRENADELAUNCHER"))] = "Grenade Launcher",
    [tostring(GetHashKey("WEAPON_RPG"))] = "RPG",
    [tostring(GetHashKey("WEAPON_MINIGUN"))] = "Minigun",
    [tostring(GetHashKey("WEAPON_FIREWORK"))] = "Firework Launcher",
    [tostring(GetHashKey("WEAPON_RAILGUN"))] = "Railgun",
    [tostring(GetHashKey("WEAPON_RAILGUNXM3"))] = "Railgun XM3",
    [tostring(GetHashKey("WEAPON_HOMINGLAUNCHER"))] = "Homing Launcher",
    [tostring(GetHashKey("WEAPON_COMPACTLAUNCHER"))] = "Compact Grenade Launcher",
    [tostring(GetHashKey("WEAPON_RAYMINIGUN"))] = "Widowmaker",
    [tostring(GetHashKey("WEAPON_EMPLAUNCHER"))] = "Compact EMP Launcher",
    [tostring(GetHashKey("WEAPON_SNOWLAUNCHER"))] = "Snowball Launcher",

    [tostring(GetHashKey("WEAPON_GRENADE"))] = "Grenade",
    [tostring(GetHashKey("WEAPON_STICKYBOMB"))] = "Sticky Bomb",
    [tostring(GetHashKey("WEAPON_PROXMINE"))] = "Proximity Mine",
    [tostring(GetHashKey("WEAPON_PIPEBOMB"))] = "Pipe Bomb",
    [tostring(GetHashKey("WEAPON_SMOKEGRENADE"))] = "Tear Gas",
    [tostring(GetHashKey("WEAPON_BZGAS"))] = "BZ Gas",
    [tostring(GetHashKey("WEAPON_MOLOTOV"))] = "Molotov",
    [tostring(GetHashKey("WEAPON_FIREEXTINGUISHER"))] = "Fire Extinguisher",
    [tostring(GetHashKey("WEAPON_PETROLCAN"))] = "Jerry Can",
    [tostring(GetHashKey("WEAPON_BALL"))] = "Ball",
    [tostring(GetHashKey("WEAPON_SNOWBALL"))] = "Snowball",
    [tostring(GetHashKey("WEAPON_FLARE"))] = "Flare",
    [tostring(GetHashKey("WEAPON_ACIDPACKAGE"))] = "Acid Package",
    [tostring(GetHashKey("WEAPON_BIRD_CRAP"))] = "Bird Crap",
    [tostring(GetHashKey("WEAPON_NEWSPAPER"))] = "Newspaper",

	[tostring(GetHashKey("WEAPON_FERTILIZERCAN"))] = "Fertilizer Can",
    [tostring(GetHashKey("WEAPON_HAZARDCAN"))] = "Hazardous Jerry Can",
    [tostring(GetHashKey("WEAPON_HACKINGDEVICE"))] = "Hacking Device",
    [tostring(GetHashKey("WEAPON_TRANQUILIZER"))] = "Tranquilizer Gun",
    [tostring(GetHashKey("WEAPON_STUNGUN_MP"))] = "Stun Gun (MP)",

	[tostring(GetHashKey("WEAPON_REMOTESNIPER"))] = "Remote Sniper",
    [tostring(GetHashKey("WEAPON_GRENADELAUNCHER_SMOKE"))] = "Smoke Grenade Launcher",
    [tostring(GetHashKey("WEAPON_RAMMED_BY_CAR"))] = "Rammed by Car",
    [tostring(GetHashKey("WEAPON_FIRE"))] = "Fire",
    [tostring(GetHashKey("WEAPON_HELI_CRASH"))] = "Heli Crash",
    [tostring(GetHashKey("WEAPON_RUN_OVER_BY_CAR"))] = "Run over by Car",
    [tostring(GetHashKey("WEAPON_HIT_BY_WATER_CANNON"))] = "Hit by Water Cannon",
    [tostring(GetHashKey("WEAPON_EXHAUSTION"))] = "Exhaustion",
    [tostring(GetHashKey("WEAPON_EXPLOSION"))] = "Explosion",
    [tostring(GetHashKey("WEAPON_ELECTRIC_FENCE"))] = "Electric Fence",
    [tostring(GetHashKey("WEAPON_BLEEDING"))] = "Bleeding",
    [tostring(GetHashKey("WEAPON_DROWNING_IN_VEHICLE"))] = "Drowning in Vehicle",
    [tostring(GetHashKey("WEAPON_DROWNING"))] = "Drowning",
    [tostring(GetHashKey("WEAPON_BARBED_WIRE"))] = "Barbed Wire",
    [tostring(GetHashKey("WEAPON_VEHICLE_ROCKET"))] = "Vehicle Rocket",
    [tostring(GetHashKey("VEHICLE_WEAPON_ROTORS"))] = "Rotors",
    [tostring(GetHashKey("WEAPON_ANIMAL"))] = "Animal",
    [tostring(GetHashKey("WEAPON_COUGAR"))] = "Cougar",
    [tostring(GetHashKey("WEAPON_STINGER"))] = "Stinger [Vehicle]",
    [tostring(GetHashKey("VEHICLE_WEAPON_TANK"))] = "Tank Cannon",
    [tostring(GetHashKey("VEHICLE_WEAPON_WATER_CANNON"))] = "Water Cannon",
    [tostring(GetHashKey("VEHICLE_WEAPON_PLAYER_LASER"))] = "Laser",
    [tostring(GetHashKey("VEHICLE_WEAPON_PLAYER_LAZER"))] = "Lazer",
    [tostring(GetHashKey("VEHICLE_WEAPON_PLAYER_BUZZARD"))] = "Buzzard",
    [tostring(GetHashKey("VEHICLE_WEAPON_PLAYER_HUNTER"))] = "Hunter",
    [tostring(GetHashKey("VEHICLE_WEAPON_PLANE_ROCKET"))] = "Plane Rocket",
    [tostring(GetHashKey("VEHICLE_WEAPON_SPACE_ROCKET"))] = "Space Rocket",
    [tostring(GetHashKey("WEAPON_AIR_DEFENCE_GUN"))] = "Air Defence Gun",

    [tostring(GetHashKey("AMMO_RPG"))] = "Rocket Ammo",
    [tostring(GetHashKey("AMMO_TANK"))] = "Tank Ammo",
    [tostring(GetHashKey("AMMO_SPACE_ROCKET"))] = "Space Rocket Ammo",
    [tostring(GetHashKey("AMMO_PLAYER_LASER"))] = "Player Laser Ammo",
    [tostring(GetHashKey("AMMO_ENEMY_LASER"))] = "Enemy Laser Ammo",
}

ClientTables.deatCause = {
    [GetHashKey("WEAPON_UNARMED")] = {"Beaten", "Unarmed"},
    [GetHashKey("WEAPON_CROWBAR")] = {"Beaten", "Crowbar"},
    [GetHashKey("WEAPON_BAT")] = {"Beaten", "Baseball Bat"},
    [GetHashKey("WEAPON_GOLFCLUB")] = {"Beaten", "Golf Club"},
    [GetHashKey("WEAPON_HAMMER")] = {"Beaten", "Hammer"},
    [GetHashKey("WEAPON_NIGHTSTICK")] = {"Beaten", "Nightstick"},
    [GetHashKey("WEAPON_POOLCUE")] = {"Beaten", "Pool Cue"},
    [GetHashKey("WEAPON_PIPEWRENCH")] = {"Beaten", "Wrench"},
    [GetHashKey("WEAPON_BATTLEAXE")] = {"Beaten", "Battleaxe"},
    [GetHashKey("WEAPON_FLASHLIGHT")] = {"Beaten", "Flashlight"},
    [GetHashKey("WEAPON_KNUCKLE")] = {"Beaten", "Knuckle Duster"},
    [GetHashKey("WEAPON_GARBAGEBAG")] = {"Beaten", "Garbage Bag"},
    [GetHashKey("WEAPON_CANDYCANE")] = {"Beaten", "Candy Cane"},
    [GetHashKey("WEAPON_STUNROD")] = {"Beaten", "The Shocker"},

    [GetHashKey("WEAPON_DAGGER")] = {"Stabbed", "Antique Cavalry Dagger"},
    [GetHashKey("WEAPON_KNIFE")] = {"Stabbed", "Knife"},
    [GetHashKey("WEAPON_SWITCHBLADE")] = {"Stabbed", "Switchblade"},
    [GetHashKey("WEAPON_HATCHET")] = {"Stabbed", "Hatchet"},
    [GetHashKey("WEAPON_STONE_HATCHET")] = {"Stabbed", "Stone Hatchet"},
    [GetHashKey("WEAPON_BOTTLE")] = {"Stabbed", "Bottle"},
    [GetHashKey("WEAPON_MACHETE")] = {"Stabbed", "Machete"},
    [GetHashKey("WEAPON_HANDCUFFS")] = {"Stabbed", "Handcuffs"},

    [GetHashKey("WEAPON_MOLOTOV")] = {"Torched", "Molotov"},
    [GetHashKey("WEAPON_FLAREGUN")] = {"Torched", "Flare Gun"},
    [GetHashKey("WEAPON_FLARE")] = {"Torched", "Flare"},
    [GetHashKey("WEAPON_FIREEXTINGUISHER")] = {"Torched", "Fire Extinguisher"},
    [GetHashKey("WEAPON_PETROLCAN")] = {"Torched", "Jerry Can"},
    [GetHashKey("WEAPON_FERTILIZERCAN")] = {"Torched", "Fertilizer Can"},
    [GetHashKey("WEAPON_HAZARDCAN")] = {"Torched", "Hazardous Jerry Can"},
    [GetHashKey("WEAPON_FIRE")] = {"Torched", "Fire"},

    [GetHashKey("WEAPON_SNSPISTOL")] = {"Pistolled", "SNS Pistol"},
    [GetHashKey("WEAPON_HEAVYPISTOL")] = {"Pistolled", "Heavy Pistol"},
    [GetHashKey("WEAPON_VINTAGEPISTOL")] = {"Pistolled", "Vintage Pistol"},
    [GetHashKey("WEAPON_PISTOL")] = {"Pistolled", "Pistol"},
    [GetHashKey("WEAPON_APPISTOL")] = {"Pistolled", "AP Pistol"},
    [GetHashKey("WEAPON_COMBATPISTOL")] = {"Pistolled", "Combat Pistol"},
    [GetHashKey("WEAPON_PISTOL50")] = {"Pistolled", "Pistol .50"},
    [GetHashKey("WEAPON_MARKSMANPISTOL")] = {"Pistolled", "Marksman Pistol"},
    [GetHashKey("WEAPON_REVOLVER")] = {"Pistolled", "Heavy Revolver"},
    [GetHashKey("WEAPON_DOUBLEACTION")] = {"Pistolled", "Double-Action Revolver"},
    [GetHashKey("WEAPON_STUNGUN")] = {"Pistolled", "Stun Gun"},
    [GetHashKey("WEAPON_RAYPISTOL")] = {"Pistolled", "Up-n-Atomizer"},
    [GetHashKey("WEAPON_CERAMICPISTOL")] = {"Pistolled", "Ceramic Pistol"},
    [GetHashKey("WEAPON_NAVYREVOLVER")] = {"Pistolled", "Navy Revolver"},
    [GetHashKey("WEAPON_GADGETPISTOL")] = {"Pistolled", "Perico Pistol"},
    [GetHashKey("WEAPON_PISTOLXM3")] = {"Pistolled", "WM 29 Pistol"},

    [GetHashKey("WEAPON_MICROSMG")] = {"Riddled", "Micro SMG"},
    [GetHashKey("WEAPON_SMG")] = {"Riddled", "SMG"},
    [GetHashKey("WEAPON_MACHINEPISTOL")] = {"Riddled", "Machine Pistol"},
    [GetHashKey("WEAPON_MINISMG")] = {"Riddled", "Mini SMG"},
    [GetHashKey("WEAPON_ASSAULTSMG")] = {"Riddled", "Assault SMG"},
    [GetHashKey("WEAPON_COMBATPDW")] = {"Riddled", "Combat PDW"},
    [GetHashKey("WEAPON_TECPISTOL")] = {"Riddled", "Tactical SMG"},

    [GetHashKey("WEAPON_CARBINERIFLE")] = {"Rifled", "Carbine Rifle"},
    [GetHashKey("WEAPON_MUSKET")] = {"Rifled", "Musket"},
    [GetHashKey("WEAPON_ADVANCEDRIFLE")] = {"Rifled", "Advanced Rifle"},
    [GetHashKey("WEAPON_ASSAULTRIFLE")] = {"Rifled", "Assault Rifle"},
    [GetHashKey("WEAPON_SPECIALCARBINE")] = {"Rifled", "Special Carbine"},
    [GetHashKey("WEAPON_COMPACTRIFLE")] = {"Rifled", "Compact Rifle"},
    [GetHashKey("WEAPON_BULLPUPRIFLE")] = {"Rifled", "Bullpup Rifle"},
    [GetHashKey("WEAPON_MILITARYRIFLE")] = {"Rifled", "Military Rifle"},
    [GetHashKey("WEAPON_HEAVYRIFLE")] = {"Rifled", "Heavy Rifle"},
    [GetHashKey("WEAPON_TACTICALRIFLE")] = {"Rifled", "Service Carbine"},
    [GetHashKey("WEAPON_BATTLERIFLE")] = {"Rifled", "Battle Rifle"},
    [GetHashKey("WEAPON_STRICKLER")] = {"Rifled", "El Strickler"},

    [GetHashKey("WEAPON_MG")] = {"Machine Gunned", "MG"},
    [GetHashKey("WEAPON_COMBATMG")] = {"Machine Gunned", "Combat MG"},
    [GetHashKey("WEAPON_GUSENBERG")] = {"Machine Gunned", "Gusenberg Sweeper"},
    [GetHashKey("WEAPON_RAYCARBINE")] = {"Machine Gunned", "Unholy Hellbringer"},

    [GetHashKey("WEAPON_BULLPUPSHOTGUN")] = {"Pulverized", "Bullpup Shotgun"},
    [GetHashKey("WEAPON_ASSAULTSHOTGUN")] = {"Pulverized", "Assault Shotgun"},
    [GetHashKey("WEAPON_DBSHOTGUN")] = {"Pulverized", "Double Barrel Shotgun"},
    [GetHashKey("WEAPON_PUMPSHOTGUN")] = {"Pulverized", "Pump Shotgun"},
    [GetHashKey("WEAPON_HEAVYSHOTGUN")] = {"Pulverized", "Heavy Shotgun"},
    [GetHashKey("WEAPON_SAWNOFFSHOTGUN")] = {"Pulverized", "Sawed-Off Shotgun"},
    [GetHashKey("WEAPON_AUTOSHOTGUN")] = {"Pulverized", "Sweeper Shotgun"},
    [GetHashKey("WEAPON_COMBATSHOTGUN")] = {"Pulverized", "Combat Shotgun"},

    [GetHashKey("WEAPON_MARKSMANRIFLE")] = {"Sniped", "Marksman Rifle"},
    [GetHashKey("WEAPON_SNIPERRIFLE")] = {"Sniped", "Sniper Rifle"},
    [GetHashKey("WEAPON_HEAVYSNIPER")] = {"Sniped", "Heavy Sniper"},
    [GetHashKey("WEAPON_REMOTESNIPER")] = {"Sniped", "Remote Sniper"},
    [GetHashKey("WEAPON_PRECISIONRIFLE")] = {"Sniped", "Precision Rifle"},

    [GetHashKey("WEAPON_GRENADELAUNCHER")] = {"Obliterated", "Grenade Launcher"},
    [GetHashKey("WEAPON_RPG")] = {"Obliterated", "RPG"},
    [GetHashKey("WEAPON_HOMINGLAUNCHER")] = {"Obliterated", "Homing Launcher"},
    [GetHashKey("WEAPON_FIREWORK")] = {"Obliterated", "Firework Launcher"},
    [GetHashKey("VEHICLE_WEAPON_TANK")] = {"Obliterated", "Tank Shell"},
    [GetHashKey("WEAPON_RAILGUN")] = {"Obliterated", "Railgun"},
    [GetHashKey("WEAPON_RAILGUNXM3")] = {"Obliterated", "Railgun XM3"},
    [GetHashKey("WEAPON_COMPACTLAUNCHER")] = {"Obliterated", "Compact Grenade Launcher"},
    [GetHashKey("WEAPON_RAYMINIGUN")] = {"Obliterated", "Widowmaker"},
    [GetHashKey("WEAPON_EMPLAUNCHER")] = {"Obliterated", "Compact EMP Launcher"},
    [GetHashKey("WEAPON_SNOWLAUNCHER")] = {"Obliterated", "Snowball Launcher"},

    [GetHashKey("WEAPON_MINIGUN")] = {"Shredded", "Minigun"},

    [GetHashKey("WEAPON_GRENADE")] = {"Bombed", "Grenade"},
    [GetHashKey("WEAPON_PROXMINE")] = {"Bombed", "Proximity Mine"},
    [GetHashKey("WEAPON_EXPLOSION")] = {"Bombed", "Explosion"},
    [GetHashKey("WEAPON_STICKYBOMB")] = {"Bombed", "Sticky Bomb"},
    [GetHashKey("WEAPON_PIPEBOMB")] = {"Bombed", "Pipe Bomb"},
    [GetHashKey("WEAPON_SMOKEGRENADE")] = {"Bombed", "Tear Gas"},
    [GetHashKey("WEAPON_BZGAS")] = {"Bombed", "BZ Gas"},
    [GetHashKey("WEAPON_ACIDPACKAGE")] = {"Bombed", "Acid Package"},

    [GetHashKey("VEHICLE_WEAPON_ROTORS")] = {"Mowed Down", "Helicopter Rotors"},
    [GetHashKey("WEAPON_RUN_OVER_BY_CAR")] = {"Flattened", "Vehicle"},
    [GetHashKey("WEAPON_RAMMED_BY_CAR")] = {"Flattened", "Vehicle"},
    [GetHashKey("WEAPON_HIT_BY_WATER_CANNON")] = {"Blasted", "Water Cannon"},
    [GetHashKey("WEAPON_ELECTRIC_FENCE")] = {"Electrocuted", "Electric Fence"},
    [GetHashKey("WEAPON_BARBED_WIRE")] = {"Impaled", "Barbed Wire"},
    [GetHashKey("WEAPON_ANIMAL")] = {"Mauled", "Animal"},
    [GetHashKey("WEAPON_COUGAR")] = {"Mauled", "Cougar"},
    [GetHashKey("WEAPON_DROWNING")] = {"Drowned", nil},
    [GetHashKey("WEAPON_DROWNING_IN_VEHICLE")] = {"Drowned", "In Vehicle"},
    [GetHashKey("WEAPON_EXHAUSTION")] = {"Exhausted", nil},
    [GetHashKey("WEAPON_BLEEDING")] = {"Bled Out", nil},
    [GetHashKey("WEAPON_HELI_CRASH")] = {"Killed in Helicopter Crash", nil},
    [GetHashKey("WEAPON_AIR_DEFENCE_GUN")] = {"Obliterated", "Air Defence Gun"},

    [-842959696] = {"Fell from a high place", nil},
}